# Generated by Django 4.2 on 2024-01-12 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Farm360", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("livestock_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("identification_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alive", "Alive"),
                            ("sold", "Sold"),
                            ("slaughtered", "Slaughtered"),
                        ],
                        default="alive",
                        max_length=20,
                    ),
                ),
                ("physical_characteristics", models.TextField()),
                ("birth_date", models.DateField()),
                ("vet_contacts", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
